# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Page(object):
    def setupUi(self, Login_Page):
        Login_Page.setObjectName("Login_Page")
        Login_Page.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(Login_Page)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setGeometry(QtCore.QRect(170, 90, 251, 21))
        self.line_login.setObjectName("line_login")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(170, 150, 251, 21))
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        Login_Page.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Page)
        QtCore.QMetaObject.connectSlotsByName(Login_Page)

    def retranslateUi(self, Login_Page):
        _translate = QtCore.QCoreApplication.translate
        Login_Page.setWindowTitle(_translate("Login_Page", "MainWindow"))
        self.label_2.setText(_translate("Login_Page", "Пароль"))
        self.pushButton.setText(_translate("Login_Page", "Войти"))
        self.label.setText(_translate("Login_Page", "Логин"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Page = QtWidgets.QMainWindow()
    ui = Ui_Login_Page()
    ui.setupUi(Login_Page)
    Login_Page.show()
    sys.exit(app.exec_())
